### ISSUE TITLE
Remove hard coded sender ID and user ID

### ISSUE THREAD

**Issue by jimmymcpeter** [austocratic/acc-connector#1]
@austocratic - Sage Intacct's monitoring tool threw an alert for this repository's code.  I'm glad to see you have not hard coded any passwords.  However, you have exposed your sender ID and user ID.  You should really move these out to environment variables as well.

https://github.com/austocratic/acc-connector/blob/b7248fcff9371495c6b4b5a6d9f5427174f6d182/libraries/intacct.js#L14-L23

**Comment by austocratic** [comment]
Thanks for being proactive about this.  I've moved sender & user IDs to env variables as you recommended.

I will close this issue
